version: '3'
services:
  service-registry:
    container_name: eureka
    network_mode: host
    build:
      context: "./service-registry"
    ports:
      - 8761:8761
  cloud-config-server:
    container_name: cloud-config
    network_mode: host
    build:
      context: ./cloud-config-server
    ports:
      - 9296:9296
    depends_on:
      - service-registry

  cloud-gateway:
    container_name: cloud-gateway
    network_mode: host
    build:
      context: ./cloud-gateway
    ports:
      - 9191:9191
    depends_on:
      - service-registry
  hotels-service:
    container_name: hotels-service
    network_mode: host
    build:
      context: ./hotels-service
    ports:
      - 9003:9003
    depends_on:
      - service-registry
  user-service:
    container_name: user-service
    network_mode: host
    build:
      context: ./user-service
    ports:
      - 9002:9002
    depends_on:
      - service-registry
