server:
  port: 9003

spring:
  application:
    name: HOTEL-SERVICE
#   cloud:
#     config:
#       discovery:
#         enabled: true
#         uri: http://localhost:9296 - ova go ima vo bootstrap

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost - ova go ima vo application.yml nadvor od proektite
